n = input('Digita algo aí: ')
print('O tipo primitivo desse valor é,', type(n))
print('É alfanumérico? ', n.isalnum())
print('É alfabético? ', n.isalpha())
print('É valor ascii? ', n.isascii())
print('É decimal? ', n.isdecimal())
print('É um dígito? ', n.isdigit())
print('É identificador? ', n.isidentifier())
print('É minúsculo? ', n.islower())
print('É numérico? ', n.isnumeric())
print('É imprimível? ', n.isprintable())
print('É um espaço? ', n.isspace())
print('É maiúsculo? ', n.isupper())
print('É título? ', n.istitle())
